import jsPDF from "jspdf";
import type { Prediction } from "@/hooks/useClassifier";

interface ExportData {
  predictions: Prediction[];
  timestamp: Date;
  scanType: "camera" | "upload";
}

export function generatePDFReport({ predictions, timestamp, scanType }: ExportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(0, 100, 200);
  doc.rect(0, 0, pageWidth, 40, "F");
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("MedScan AI Pro", pageWidth / 2, 20, { align: "center" });
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Radiology Decision Support Report", pageWidth / 2, 30, { align: "center" });

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Report Info
  let yPos = 55;
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Report Generated: ${timestamp.toLocaleString()}`, 20, yPos);
  doc.text(`Scan Type: ${scanType === "camera" ? "Live Camera" : "Image Upload"}`, 20, yPos + 7);
  
  yPos += 25;

  // Classification Results Header
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text("Classification Results", 20, yPos);
  
  yPos += 15;

  // Top Prediction Box
  if (predictions.length > 0) {
    const topPred = predictions[0];
    const confidence = Math.round(topPred.probability * 100);
    
    doc.setFillColor(230, 245, 255);
    doc.roundedRect(20, yPos, pageWidth - 40, 35, 3, 3, "F");
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 80, 160);
    doc.text("Primary Finding", 30, yPos + 12);
    
    doc.setFontSize(18);
    doc.setTextColor(0, 0, 0);
    doc.text(topPred.className, 30, yPos + 25);
    
    // Confidence
    const confidenceColor = confidence >= 70 ? [34, 139, 34] : confidence >= 40 ? [255, 165, 0] : [220, 53, 69];
    doc.setTextColor(confidenceColor[0], confidenceColor[1], confidenceColor[2]);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text(`${confidence}%`, pageWidth - 40, yPos + 20, { align: "right" });
    
    yPos += 45;
  }

  // All Classifications
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(0, 0, 0);
  doc.text("All Classifications", 20, yPos);
  
  yPos += 10;

  predictions.forEach((pred, index) => {
    const confidence = Math.round(pred.probability * 100);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(60, 60, 60);
    doc.text(`${index + 1}. ${pred.className}`, 25, yPos);
    doc.text(`${confidence}%`, pageWidth - 25, yPos, { align: "right" });
    
    // Progress bar background
    doc.setFillColor(230, 230, 230);
    doc.roundedRect(25, yPos + 3, 120, 4, 1, 1, "F");
    
    // Progress bar fill
    const barColor = confidence >= 70 ? [34, 139, 34] : confidence >= 40 ? [255, 165, 0] : [220, 53, 69];
    doc.setFillColor(barColor[0], barColor[1], barColor[2]);
    doc.roundedRect(25, yPos + 3, (confidence / 100) * 120, 4, 1, 1, "F");
    
    yPos += 15;
  });

  // Disclaimer
  yPos += 20;
  doc.setFillColor(255, 243, 205);
  doc.roundedRect(20, yPos, pageWidth - 40, 30, 3, 3, "F");
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(133, 100, 4);
  doc.text("⚠ Medical Disclaimer", 25, yPos + 10);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  const disclaimerText = "For triage assistance only. This tool is a prototype and does not replace a professional radiologist's diagnosis. Always consult qualified medical professionals for clinical decisions.";
  const splitDisclaimer = doc.splitTextToSize(disclaimerText, pageWidth - 50);
  doc.text(splitDisclaimer, 25, yPos + 18);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by MedScan AI Pro - Powered by TensorFlow.js", pageWidth / 2, pageHeight - 10, { align: "center" });

  // Save the PDF
  const fileName = `medscan-report-${timestamp.toISOString().split("T")[0]}.pdf`;
  doc.save(fileName);
}
